# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0070_auto_20160224_1140'),
    ]

    operations = [
    migrations.RunSQL('''
            CREATE OR REPLACE FUNCTION get_all_workers_ratings()
                RETURNS TABLE(worker_id INTEGER, requester_id INTEGER, task_status INTEGER, requester_rating DOUBLE PRECISION,
                requester_avg_rating DOUBLE PRECISION)
                AS $$
               select p.worker_id, p.owner_id, p.task_status, q.weight, q.average_rating from
( select a.worker_id worker_id, c.owner_id owner_id, a.task_status task_status from crowdsourcing_taskworker a INNER JOIN crowdsourcing_task b ON a.task_id = b.id INNER JOIN crowdsourcing_project c ON b.project_id = c.id) p

INNER JOIN
( SELECT
                     r.id                                            requester_id,
                     worker_ratings.target_id                        target_id,
                     worker_ratings.weight                           weight,
                     CASE WHEN worker_ratings.number_of_ratings = 1
                       THEN worker_ratings.avg_rw_rating
                    
                     ELSE (worker_ratings.avg_rw_rating * worker_ratings.number_of_ratings - worker_ratings.weight) /
                          (worker_ratings.number_of_ratings - 1) END average_rating
                   FROM crowdsourcing_requester r LEFT OUTER JOIN (
                                                                    SELECT
                                                                      wrr.target_id,
                                                                      wrr.origin_id,
                                                                      wrr.weight,
                                                                      avg_rw_rating,
                                                                      number_of_ratings
                                                                    FROM crowdsourcing_workerrequesterrating wrr
                                                                      INNER JOIN (
                                                                                   SELECT
                                                                                     recent_req_rating.target_id,
                                                                                     AVG(recent_req_rating.weight) AS avg_rw_rating,
                                                                                     COUNT(
                                                                                         recent_req_rating.target_id) number_of_ratings
                                                                                   FROM (
                                                                                          SELECT
                                                                                            wrr.weight,
                                                                                            wrr.target_id
                                                                                          FROM
                                                                                            crowdsourcing_workerrequesterrating wrr
                                                                                            INNER JOIN (
                                                                                                         SELECT
                                                                                                           origin_id,
                                                                                                           target_id,
                                                                                                           MAX(
                                                                                                               last_updated) AS max_date
                                                                                                         FROM
                                                                                                           crowdsourcing_workerrequesterrating
                                                                                                         WHERE  origin_type='requester'
                                                                                                         GROUP BY origin_id,
                                                                                                           target_id
                                                                                                       ) most_recent
                                                                                              ON most_recent.origin_id =
                                                                                                 wrr.origin_id AND
                                                                                                 most_recent.target_id =
                                                                                                 wrr.target_id
                                                                                                 AND
                                                                                                 wrr.last_updated =
                                                                                                 most_recent.max_date
                                                                                                 
                                                                                                 AND wrr.origin_type =
                                                                                                     'requester') recent_req_rating
                                                                                   GROUP BY recent_req_rating.target_id
                                                                                 ) avg_rw_rating
                                                                        ON wrr.target_id = avg_rw_rating.target_id
                                                                      INNER JOIN (
                                                                                   SELECT
                                                                                     origin_id,
                                                                                     target_id,
                                                                                     MAX(last_updated) AS max_date
                                                                                   FROM crowdsourcing_workerrequesterrating
                                                                                   WHERE origin_type='requester'
                                                                                   GROUP BY origin_id, target_id
                                                                                 ) most_recent
                                                                        ON wrr.origin_id = most_recent.origin_id AND
                                                                           wrr.target_id = most_recent.target_id AND
                                                                           wrr.last_updated = most_recent.max_date AND
                                                                           wrr.origin_type = 'requester') worker_ratings
                       ON r.profile_id = worker_ratings.origin_id) q
                       ON p.worker_id = q.target_id 
                       AND p.owner_id = q.requester_id;
                $$
            LANGUAGE SQL
            STABLE
            RETURNS NULL ON NULL INPUT;
        ''')
    ]
